Update s3-cloudfront-website module to use non-Github source
The version lock, under Terraform 0.12, doesn't work when the source is
Github.

Error: Invalid version constraint

Cannot apply a version constraint to module "site" (at
.terraform/modules/openoakland_org.site/s3_cloudfront_website/main.tf:9)
because it has a non Registry URL.